In [62]:
import SingleHouseModel
import numpy
SOC = 0.2
[a,b] = SingleHouseModel.bidding_scheme(0.5, 200)
# print(bidding_schemes[1])
print([a,b])

[-11.0632183908046, 1.1364942528735633]


In [77]:
import numpy
c = numpy.random.rand(2,4,6)
# print(c)
# print(c[0:2, 1, 1])
# c[0:2, 1, 1] = [a, b]
# print([a,b])
# print(c[0:2, 1, 1])
d = c[0:2, :, 1]
# print(d)
# print(d[:,0])
print(c)
c[1, :, 5] = 1
print(c)

[[[0.94102243 0.1240698  0.40063494 0.02993803 0.7029857  0.6292874 ]
  [0.81911958 0.11928306 0.03019391 0.26319519 0.67924536 0.33891443]
  [0.69912706 0.08508996 0.71006462 0.64725012 0.01824045 0.57716285]
  [0.17860639 0.1750949  0.546416   0.83785276 0.23869531 0.9680457 ]]

 [[0.70361402 0.7328556  0.97644992 0.40192862 0.2800292  0.41246258]
  [0.06760188 0.02447985 0.43266005 0.43399848 0.14557689 0.94620249]
  [0.20014575 0.51281335 0.54046923 0.002345   0.95383558 0.1433802 ]
  [0.68610001 0.59412466 0.95110221 0.34675559 0.92282699 0.69305829]]]
[[[0.94102243 0.1240698  0.40063494 0.02993803 0.7029857  0.6292874 ]
  [0.81911958 0.11928306 0.03019391 0.26319519 0.67924536 0.33891443]
  [0.69912706 0.08508996 0.71006462 0.64725012 0.01824045 0.57716285]
  [0.17860639 0.1750949  0.546416   0.83785276 0.23869531 0.9680457 ]]

 [[0.70361402 0.7328556  0.97644992 0.40192862 0.2800292  1.        ]
  [0.06760188 0.02447985 0.43266005 0.43399848 0.14557689 1.        ]
  [0.20014575 

In [49]:
if 1!=0:
    print("123")

123


In [51]:
a= range(10)
print(sum(a))

45


In [70]:
import Aggregator
agg_decision = Aggregator.AggregatorDecision(d, 1)
print(agg_decision.price())
print(agg_decision.energy_distribution())

0.03
[0.720801922264564, 0.5152376315684639, 0.6689610543414861, 0.389164721321924]


In [ ]:
a= [1  2 3]
b=[4 6 5]